### ISSUE TITLE
Widget not showing any world states on Pilot C wirecloud instance

### ISSUE THREAD

**Issue by DenoBeno** [crismaproject/worldstate-tree-widget-wirecloud#2]
I tried to use this within Pilot C setting on https://crisma-pilotc.ait.ac.at/wirecloud/pilotC/Indicators#view=workspace&market=local&subview=search, but the widget isn't showing any states at all. 

Tried: 
- with default settings (points to cismet ICMM instance)
- changing the ICMM uri to pilot C specific instance
- using http://crisma.cismet.de/icmm_api/images/ or http://crisma.cismet.de/images/ as image path.

**Comment by mscholl** [comment]
The issue here is the mixed content loading. The default ICMM instance is not served via https while the widget itself is (as the wirecloud instance is). This leads to mixed content loading warnings that effectively block the loading from the unsecured resource. In Chrome e.g. there is such an icon in the addressbar:

![screen shot 2015-04-02 at 09 04 43](https://cloud.githubusercontent.com/assets/973421/6959534/7486ec16-d91a-11e4-96e7-1a0b07e894fb.png)

You have to allow the loading of unsafe scripts:

![screen shot 2015-04-02 at 09 21 02](https://cloud.githubusercontent.com/assets/973421/6959541/88ad43d4-d91a-11e4-859a-77fc1ce848c6.png)

Et voilà:

![screen shot 2015-04-02 at 09 21 47](https://cloud.githubusercontent.com/assets/973421/6959557/a2acad88-d91a-11e4-92d8-12f2b7db42c5.png)

I tried the Pilot C instance and it does not work because of an error. This is the result of incomplete CCIM information. See Pilot E instance where the widget is used for the control of the analysis widgets. Please also note that changing any settings in wirecloud requires a widget reload!

The image path is a completely different thing: it is neither relative to the ICMM nor does it have any relation to it. It is simply the base path for the images of the nodes e.g. world_leaf_16.png for leaf nodes of the tree. The path is relative to the source of the page not to the ICMM instance. You can also use absolute paths to point to images, etc. However, if there are no nodes displayed there are no images also, obviously.
